### ISSUE TITLE
Support subdirectories & manipulation syntax

### ISSUE THREAD

**Issue by bitbrain** [jverhoelen/golumbus#2]
Given is the following folder structure:

```
~/A/
├── B/
├── C/
```

Also a location `'ALocation'` exists which references the `A` folder. As a user when I type the following:

``` bash
go 'ALocation'/B
```

I want to move directly into the `B` folder which is located inside the `A` folder.
# Jumping to parent

``` bash
go 'ALocation'/..
```

would move to the parent directory of `A`.

``` bash
go 'ALocation'/B/..
```

would be equivalent to

``` bash
go 'ALocation'
```

_Is this idea feasible or completely not possible to implement?_

**Comment by jonas-pietzsch** [comment]
(Please note that the `go 'location'` only looks up the path to jump to. You need to make an integration into your command line. Just to make clarify the usage of "jumping")

Of course I get the idea of your feature request to build some extended "path manipulation mechanism" into the command to evaluate target-relative paths quickly, too.
Due to the fact that also `go alocation` works to lookup for the path "alocation", we would need some kind of separator between target name and additional manipulation syntax, right?
For example defining "/" as a symbol that indicates following manipulation expressions.

And, of course it's possible and also feasible! Let's tackle it.

**Comment by jonas-pietzsch** [comment]
Auto-completion seems to be a very hot topic being connected with a lot of shell work. I think this is out of scope for this module.

**Comment by jonas-pietzsch** [comment]
This is about to be released now. Luckily I only had to care about concatenating the resulting path to the manipulation syntax and the ´cd´ command really takes the remaining work 👍
